### ISSUE TITLE
issues with the sort_vertices_of_regions()

### ISSUE THREAD

**Issue by ggautreau** [niknow/pydata-london-2016-voronoi#1]
Hello,

When i run this simple portion of code 
```

import numpy as np
from scipy.spatial import SphericalVoronoi, distance
from scipy.spatial import _spherical_voronoi as spherical_voronoi

test = np.array([[-0.1382177 , -0.66701253,  0.36649207],
       [-0.33718559, -0.0515926 ,  0.7109696 ],
       [-0.13633904, -0.65712506,  0.3830903 ],
       [ 0.04510981,  0.72285262,  0.35677763],
       [-0.14008791, -0.65997704,  0.37445958],
       [-0.7253343 , -0.26837762,  0.00655405],
       [-0.58085674, -0.40511863, -0.36093304],
       [ 0.2780397 ,  0.72729778,  0.24511902],
       [-0.33315233, -0.16453994, -0.6972229 ],
       [-0.46532148,  0.35901168, -0.45935981],
       [-0.72827086, -0.25884677, -0.00137087],
       [-0.72758263, -0.25989862,  0.00278446],
       [-0.70204518, -0.31395337, -0.0467136 ],
       [-0.71771464, -0.28226784, -0.01436788],
       [-0.72884793, -0.25239507,  0.01278218],
       [-0.72528059, -0.26018933, -0.00931674],
       [ 0.23175783, -0.68754004,  0.24004559],
       [ 0.69090723, -0.2371959 , -0.19492292],
       [ 0.40653046, -0.63173528, -0.25505239],
       [ 0.53203067, -0.52945865, -0.14520801],
       [ 0.52527016, -0.53501648, -0.2155609 ],
       [ 0.56226738, -0.31942141, -0.39975375]])
	   
sv = SphericalVoronoi(test)
sv.sort_vertices_of_regions()
```

I get the following error :

```
Python 2.7.12 |Anaconda custom (64-bit)| (default, Jul  2 2016, 17:42:40) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://anaconda.org
>>> import numpy as np
>>> from scipy.spatial import SphericalVoronoi, distance
>>> from scipy.spatial import _spherical_voronoi as spherical_voronoi
>>>
>>> test = np.array([[-0.1382177 , -0.66701253,  0.36649207],
...        [-0.33718559, -0.0515926 ,  0.7109696 ],
...        [-0.13633904, -0.65712506,  0.3830903 ],
...        [ 0.04510981,  0.72285262,  0.35677763],
...        [-0.14008791, -0.65997704,  0.37445958],
...        [-0.7253343 , -0.26837762,  0.00655405],
...        [-0.58085674, -0.40511863, -0.36093304],
...        [ 0.2780397 ,  0.72729778,  0.24511902],
...        [-0.33315233, -0.16453994, -0.6972229 ],
...        [-0.46532148,  0.35901168, -0.45935981],
...        [-0.72827086, -0.25884677, -0.00137087],
...        [-0.72758263, -0.25989862,  0.00278446],
...        [-0.70204518, -0.31395337, -0.0467136 ],
...        [-0.71771464, -0.28226784, -0.01436788],
...        [-0.72884793, -0.25239507,  0.01278218],
...        [-0.72528059, -0.26018933, -0.00931674],
...        [ 0.23175783, -0.68754004,  0.24004559],
...        [ 0.69090723, -0.2371959 , -0.19492292],
...        [ 0.40653046, -0.63173528, -0.25505239],
...        [ 0.53203067, -0.52945865, -0.14520801],
...        [ 0.52527016, -0.53501648, -0.2155609 ],
...        [ 0.56226738, -0.31942141, -0.39975375]])
>>> 
>>> sv = SphericalVoronoi(test)
>>> sv.sort_vertices_of_regions()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/env/export/cns_n02_agc/agc/home/ggautrea/anaconda2/lib/python2.7/site-packages/scipy/spatial/_spherical_voronoi.py", line 319, in sort_vertices_of_regions
    ][0]
IndexError: list index out of range
```

Can you help me ?
Thank you.

**Comment by ggautreau** [comment]
When i round the array with only 3 decimals, it works.

```
import numpy as np
from scipy.spatial import SphericalVoronoi, distance
from scipy.spatial import _spherical_voronoi as spherical_voronoi

test = np.array([[-0.1382177 , -0.66701253,  0.36649207],
       [-0.33718559, -0.0515926 ,  0.7109696 ],
       [-0.13633904, -0.65712506,  0.3830903 ],
       [ 0.04510981,  0.72285262,  0.35677763],
       [-0.14008791, -0.65997704,  0.37445958],
       [-0.7253343 , -0.26837762,  0.00655405],
       [-0.58085674, -0.40511863, -0.36093304],
       [ 0.2780397 ,  0.72729778,  0.24511902],
       [-0.33315233, -0.16453994, -0.6972229 ],
       [-0.46532148,  0.35901168, -0.45935981],
       [-0.72827086, -0.25884677, -0.00137087],
       [-0.72758263, -0.25989862,  0.00278446],
       [-0.70204518, -0.31395337, -0.0467136 ],
       [-0.71771464, -0.28226784, -0.01436788],
       [-0.72884793, -0.25239507,  0.01278218],
       [-0.72528059, -0.26018933, -0.00931674],
       [ 0.23175783, -0.68754004,  0.24004559],
       [ 0.69090723, -0.2371959 , -0.19492292],
       [ 0.40653046, -0.63173528, -0.25505239],
       [ 0.53203067, -0.52945865, -0.14520801],
       [ 0.52527016, -0.53501648, -0.2155609 ],
       [ 0.56226738, -0.31942141, -0.39975375]])
	   
test = np.round(test,3)	   
	  
sv = SphericalVoronoi(test)
sv.sort_vertices_of_regions()
```

**Comment by ggautreau** [comment]
Finally after several tests even when I round the numpy array, I have issues again.

For example with this rounded array (which is the same as before with 5 lines added), I have the same error (list index out of range):

```
np.array([[-0.138, -0.667,  0.366],
       [-0.337, -0.052,  0.711],
       [-0.136, -0.657,  0.383],
       [ 0.045,  0.723,  0.357],
       [-0.14 , -0.66 ,  0.374],
       [-0.725, -0.268,  0.007],
       [-0.581, -0.405, -0.361],
       [ 0.278,  0.727,  0.245],
       [-0.333, -0.165, -0.697],
       [-0.465,  0.359, -0.459],
       [-0.728, -0.259, -0.001],
       [-0.728, -0.26 ,  0.003],
       [-0.702, -0.314, -0.047],
       [-0.718, -0.282, -0.014],
       [-0.729, -0.252,  0.013],
       [-0.725, -0.26 , -0.009],
       [ 0.232, -0.688,  0.24 ],
       [ 0.691, -0.237, -0.195],
       [ 0.407, -0.632, -0.255],
       [ 0.532, -0.529, -0.145],
       [ 0.525, -0.535, -0.216],
       [ 0.562, -0.319, -0.4  ],
       [ 0.642, -0.401,  0.052],
       [-0.657, -0.381, -0.2  ],
       [-0.237, -0.081, -0.742],
       [-0.476,  0.08 , -0.598],
       [-0.332,  0.052, -0.691]])
```

**Comment by ggautreau** [comment]
The discussion is available here https://github.com/scipy/scipy/issues/7046

**Comment by niknow** [comment]
Hi,

thanks for your detailled feedback. I'm very very sorry that it took me so long to reply. As this repo is only about the presentation, you were absolutely correct in opening an issue in the the scipy repo. I can see there that my co-authors have addressed your question. Thanks for using the library!
